import React from "react";
import styles from "./Community.module.css";
import Head from "next/head";
import homeStyles from "@/styles/Home.module.css";
import Image from "next/image";
import { CommunityPage } from "@/components/CommunityPage";
import { Group } from "@/models/group";
import { Footer } from "@/components/Footer";

export interface CommunityProps {
  group: Group;
}

export const Community = ({ group }: CommunityProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={homeStyles.main}>
        <div className={homeStyles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By future{" "}
              <Image
                src="/skool.svg"
                alt="Skool Logo"
                className={homeStyles.skoolLogo}
                width={100}
                height={24}
                priority
              />
              er
            </a>
          </div>
        </div>

        <CommunityPage
          id={group.name}
          title={group.metadata.displayName}
          logo={group.metadata.logoUrl}
          headerImg={group.metadata.coverSmallUrl}
          description={group.metadata.description}
          accessType={group.metadata.lpAccessType}
          numberOfMembers={group.metadata.totalMembers}
          isPublic={group.metadata.public}
        />

        <Footer />
      </main>
    </>
  );
};
