import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { CommunityCard } from "@/components/CommunityCard";
import { Group } from "@/models/group";
import { NextPageContext } from "next";
import { getDiscoveryGroups } from "@/dataFetchers/api";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: NextPageContext) {
  const discovery = await getDiscoveryGroups();

  return { props: { groups: discovery.pageProps.groups } };
}

interface HomeProps {
  groups: Array<{
    group: Group;
    rank: number;
  }>;
}

export default function Home({ groups }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By future{" "}
              <Image
                src="/skool.svg"
                alt="Skool Logo"
                className={styles.skoolLogo}
                width={100}
                height={24}
                priority
              />
              er
            </a>
          </div>
        </div>

        <div className={`${styles.discoveryCards}`}>
          {groups.map((groupItem) => {
            const group = groupItem.group;
            return (
              <Link href={`/${groupItem.group.name}`} key={groupItem.group.id}>
                <CommunityCard
                  id={groupItem.group.name}
                  title={group.metadata.displayName}
                  logo={group.metadata.logoUrl}
                  headerImg={group.metadata.coverSmallUrl}
                  description={group.metadata.description}
                  accessType={group.metadata.lpAccessType}
                  numberOfMembers={group.metadata.totalMembers}
                  isPublic={group.metadata.public}
                />
              </Link>
            );
          })}
        </div>

        <Footer />
      </main>
    </>
  );
}
